package:
  name: boost
  version: "1.59.0"

source:
  fn: boost_1_59_0.zip  # [win]
  url: http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.zip/download  # [win]
  sha1: 6950ff432f1d7b7134b452e9870fe627f76e42a7  # [win]
  fn: boost_1_59_0.tar.gz  # [unix]
  url: http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download  # [unix]
  sha1: 5123209db194d66d69a9cfa5af8ff473d5941d97  # [unix]

build:
  number: 0

requirements:
  build:
    - python
    - bzip2 1.0.*
    - zlib 1.2.*

  run:
    - python
    - bzip2 1.0.*
    - zlib 1.2.*

about:
  home: http://www.boost.org/
  license: Boost Software License
